### ISSUE TITLE
Add a note explaining that pingpong.yaml needs editing with the TPP url before you apply it

### ISSUE THREAD

**Issue by wallrj** [jetstack/cert-manager-nginx-plus-lab#41]
It contains 

```
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: venafi-tpp-pingpong-issuer
  namespace: default
spec:
  venafi:
    zone: "TLS/SSL\\Certificates\\Jetstack-short"
    tpp:
      url: https://<instance hostname>/vedsdk # Change this to the URL of your TPP instance
      credentialsRef:
        name: tpp-auth-secret

```
